//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.9.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:\Users\Belkis Vasquez\source\repos\ProyectoMedioTerminoG6\ProyectoMedioTerminoG6\Proyecto.g4 by ANTLR 4.9.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="ProyectoParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.9.2")]
[System.CLSCompliant(false)]
public interface IProyectoVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] ProyectoParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.script"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitScript([NotNull] ProyectoParser.ScriptContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.host"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitHost([NotNull] ProyectoParser.HostContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.become"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBecome([NotNull] ProyectoParser.BecomeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.tasks_lb"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTasks_lb([NotNull] ProyectoParser.Tasks_lbContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.tasks"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTasks([NotNull] ProyectoParser.TasksContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitName([NotNull] ProyectoParser.NameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="ProyectoParser.apt"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitApt([NotNull] ProyectoParser.AptContext context);
	/// <summary>
	/// Visit a parse tree produced by the <c>comando</c>
	/// labeled alternative in <see cref="ProyectoParser.command"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitComando([NotNull] ProyectoParser.ComandoContext context);
}
